GET http://localhost:3001/api/contactforms

###

POST http://localhost:3001/api/contactforms
Content-Type: application/json

{
    "email": "test@test.com",
    "message": "message"
}

###
GET http://localhost:3001/api/techcontents


###

POST http://localhost:3001/api/techcontents
Content-Type: application/json

{
    "embedUrl": "https://www.linkedin.com/posts/alexander-allen-392225251_cryptocurrency-ampleforth-ampl-activity-7059457543135252480-aDqi?utm_source=share&utm_medium=member_desktop",
    "description": "Introducing SPOT, Ampleforth's Solution to Stability in Cryptocurrency - Part 3, read on to find out more.",
    "thumbnailImageUrl": "https://www.linkedin.com/posts/alexander-allen-392225251_cryptocurrency-ampleforth-ampl-activity-7059457543135252480-aDqi?utm_source=share&utm_medium=member_desktop"
}
